### ISSUE TITLE
Some questions about "multinerf_pl/internal/coord.py"

### ISSUE THREAD

**Issue by zfw-cv** [SuLvXiangXin/multinerf-pytorch#3]
Hello author. Thank you so much for open sourcing your work. However, I have some questions in my actual running rawnerf and would like to consult you. Hope to get a reply. When running bash scripts/train_raw.sh, I keep prompting me with the following error, which I feel very strange, I want your answer, thank you。
Found no checkpoint files in exp/raw/windowlegovary with prefix checkpoint_
Number of parameters being optimized: 615740
Begin training...
  0%|                                                                                              | 0/500000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wangzhifeng/multinerf_pl/train.py", line 361, in <module>
    app.run(main)
  File "/home/wangzhifeng/.conda/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/wangzhifeng/.conda/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/wangzhifeng/multinerf_pl/train.py", line 142, in main
    renderings, ray_history = model(
  File "/home/wangzhifeng/.conda/envs/multinerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangzhifeng/multinerf_pl/internal/models.py", line 104, in forward
    _, s_to_t = coord.construct_ray_warps(self.raydist_fn, batch['near'], batch['far'])
  File "/home/wangzhifeng/multinerf_pl/internal/coord.py", line 289, in construct_ray_warps
    fn_inv = inv_mapping[fn.__name__]
AttributeError: 'str' object has no attribute '__name__'

**Comment by pedrogcmartin** [comment]
Has anyone solved this problem yet?

**Comment by luyuxuan98** [comment]
Hello, I have solved this issue. Comparing with the official Multinerf repository, the construct_ray_warps function seems to be used to adapt to different ray modeling strategies. In the official code, Rawnerf uses the default None for the model.

So, in this PyTorch version of the repository, you can either modify line 35 of multinerf-pytorch/internal/models.py to set raydist_fn = None, or add the configuration Model.raydist_fn = None in multinerf-pytorch/configs/llff_raw.gin.
